### ISSUE TITLE
"Update admin list" paragraph has a small mistake

### ISSUE THREAD

**Issue by francescozitelli** [MicrosoftDocs/powerapps-docs.it-it#2]
OnStart dropdown is included in App selector, and not in LoginScreen container.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Installare e configurare l'esempio di Help Desk per le app canvas - PowerApps](https://docs.microsoft.com/it-it/powerapps/maker/canvas-apps/help-desk-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs.it-it/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by CeciAc** [comment]
Hello, @francescozitelli 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerapps-docs/issues/406

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
